
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mcq
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTRBUTNVT1BNR0E1REpZT0c=
  AWS_SECRET_ACCESS_KEY: aUhkUFJERVdSMjE3cUZzaDRmbWtSYnJqdWd1TVNsTXVBMisrblFlOA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcq-tool
  namespace: mcq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcq-tool
  template:
    metadata:
      labels:
        app: mcq-tool
    spec:
      containers:
      - name: mcq-tool
        image: sagarmhatre/mcquery:1.8
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "ap-southeast-1"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"

  
---
apiVersion: v1
kind: Service
metadata:
  name: mcq-tool-service
  namespace: mcq
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /static/dashboard.html
spec:
  selector:
    app: mcq-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # type: LoadBalancer
  type : NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mcquery
  namespace: mcq
  annotations:
    # Load Balancer Name
    alb.ingress.kubernetes.io/load-balancer-name: ingress-mcquery
    # Ingress Core Settings
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    #Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'   
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: mcq-tool-service
      port:
        number: 80                          
  rules:
    - http:
        paths:           
          - path: /mcq
            pathType: Prefix
            backend:
              service:
                name: mcq-tool-service
                port: 
                  number: 80