
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mcq
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTRBUTNVT1BNR0E1REpZT0c=
  AWS_SECRET_ACCESS_KEY: aUhkUFJERVdSMjE3cUZzaDRmbWtSYnJqdWd1TVNsTXVBMisrblFlOA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcq-tool
  namespace: mcq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcq-tool
  template:
    metadata:
      labels:
        app: mcq-tool
    spec:
      containers:
      - name: mcq-tool
        image: sagarmhatre/mcquery:1.7
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "ap-southeast-1"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mcq-tool-hpa
  namespace: mcq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcq-tool
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 69
  
---
apiVersion: v1
kind: Service
metadata:
  name: mcq-tool-service
  namespace: mcq
spec:
  selector:
    app: mcq-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer